# Generated by Django 3.0.4 on 2021-08-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Draft', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wish_type', models.CharField(choices=[('Wishlist', 'Wishlist'), ('Other', 'Other')], default='Wishlist', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('territory', models.CharField(choices=[('PwC Mekong', 'PwC Mekong'), ('Other', 'Other')], default='PwC Mekong', max_length=100)),
                ('asignee', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code_test.Requestor')),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='code_test.Wish_status')),
            ],
        ),
    ]
